version: "3.8"

services:
  quasar-op-api:
    build: .
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      DATABASE_URL: "postgres://postgres:postgrespw@host.docker.internal:5432/postgres?sslmode=disable"
    ports:
      - 8080:8080

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  data:
